export const GET_TASKS = "GET_TASKS";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_ERROR = "GET_TASKS_ERROR";
export const GET_TASKS_CLEAR = "GET_TASKS_CLEAR";

export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_ERROR = "CREATE_TASK_ERROR";

export const SEARCH_TASKS = "SEARCH_TASKS";
export const SEARCH_TASKS_SUCCESS = "SEARCH_TASKS_SUCCESS";
export const SEARCH_TASKS_ERROR = "SEARCH_TASKS_ERROR";

export const FILTER_TASKS = "FILTER_TASKS";
export const FILTER_TASKS_SUCCESS = "FILTER_TASKS_SUCCESS";
export const FILTER_TASKS_ERROR = "FILTER_TASKS_ERROR";

export const GET_TASK = "GET_TASK";
export const GET_TASK_ERROR = "GET_TASK_ERROR";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_CLEAR = "GET_TASK_CLEAR";

export const GET_TASKS_FILES = "GET_TASKS_FILES";
export const GET_TASKS_FILES_SUCCESS = "GET_TASKS_FILES_SUCCESS";
export const GET_TASKS_FILES_ERROR = "GET_TASKS_FILES_ERROR";
export const GET_TASKS_FILES_CLEAR = "GET_TASKS_FILES_CLEAR";

export const EDIT_TASK = "EDIT_TASK";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";
export const EDIT_TASK_ERROR = "EDIT_TASK_ERROR";
export const EDIT_TASK_CLEAR = "EDIT_TASK_CLEAR";

export const GET_ACTIVITIES_LOG = "GET_ACTIVITIES_LOG";
export const GET_ACTIVITIES_LOG_SUCCESS = "GET_ACTIVITIES_LOG_SUCCESS";
export const GET_ACTIVITIES_LOG_ERROR = "GET_ACTIVITIES_LOG_ERROR";
export const GET_ACTIVITIES_LOG_CLEAR = "GET_ACTIVITIES_LOG_CLEAR";

export const EDIT_TASK_DETAILS = "EDIT_TASK_DETAILS";
export const EDIT_TASK_DETAILS_SUCCESS = "EDIT_TASK_DETAILS_SUCCESS";
export const EDIT_TASK_DETAILS_ERROR = "EDIT_TASK_DETAILS_ERROR";

export const SET_TASKS_FILES = "SET_TASKS_FILES";
export const SET_TASKS_FILES_CLEAR = "SET_TASKS_FILES_CLEAR";
