export const GET_TASKS = "GET_TASKS";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_ERROR = "GET_TASKS_ERROR";
export const GET_TASKS_CLEAR = "GET_TASKS_CLEAR";

export const CREATE_TASK = "CREATE_TASK";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_ERROR = "CREATE_TASK_ERROR";

export const SEARCH_TASKS = "SEARCH_TASKS";
export const SEARCH_TASKS_SUCCESS = "SEARCH_TASKS_SUCCESS";
export const SEARCH_TASKS_ERROR = "SEARCH_TASKS_ERROR";
