export const LOAD_MORE_REQUIRED = "LOAD_MORE_REQUIRED";
export const LOAD_END = "LOAD_END";
export const ENABLE_LOADING = "ENABLE_LOADING";
export const RESET_LOADING_STATE = "RESET_LOADING_STATE";
export const PAGE_BOTTOM_REACH = "PAGE_BOTTOM_REACH";
