export const PASSWORD_PATTERN = /^(?=.*?[a-z])(?=.*?[0-9]).{6,}$/;

export const ERRORS_CONST = {
  PASSWORD_MIN_LENGTH: 6,
  PASSWORD_MAX_LENGTH: 50,

  // Username
  USERNAME_MIN_LENGTH: 2,
  USERNAME_MAX_LENGTH: 30,

  // Title
  TITLE_MAX_LENGTH: 60,
  TITLE_MIN_LENGTH: 3,

  // Description
  DESCRIPTION_MAX_LENGTH: 500,
  TASK_DESCRIPTION_MAX_LENGTH: 3000,

  //Summary
  SUMMARY_MIN_LENGTH: 3,
  SUMMARY_MAX_LENGTH: 100,

  //Keyword
  KEYWORD_MIN_LENGTH: 3,

  // Column title
  COLUMN_MIN_LENGTH: 3,
  COLUMN_MAX_LENGTH: 20,

  //workLogComment
  WORK_LOG_COMMENT_MIN_LENGTH: 1,
  WORK_LOG_COMMENT_MAX_LENGTH: 500,
};

export const ERRORS_RULES = {
  IS_INCORRECT_LENGTH_PASSWORD: {
    PASSWORD_MIN_LENGTH: ERRORS_CONST.PASSWORD_MIN_LENGTH,
    PASSWORD_MAX_LENGTH: ERRORS_CONST.PASSWORD_MAX_LENGTH,
  },
  IS_INCORRECT_LENGTH_USERNAME: {
    USERNAME_MIN_LENGTH: ERRORS_CONST.USERNAME_MIN_LENGTH,
    USERNAME_MAX_LENGTH: ERRORS_CONST.USERNAME_MAX_LENGTH,
  },
  IS_INCORRECT_LENGTH_TITLE: {
    TITLE_MIN_LENGTH: ERRORS_CONST.TITLE_MIN_LENGTH,
    TITLE_MAX_LENGTH: ERRORS_CONST.TITLE_MAX_LENGTH,
  },
  IS_INCORRECT_LENGTH_DESCRIPTION: {
    DESCRIPTION_MAX_LENGTH: ERRORS_CONST.DESCRIPTION_MAX_LENGTH,
  },
  IS_INCORRECT_LENGTH_SUMMARY: {
    SUMMARY_MIN_LENGTH: ERRORS_CONST.SUMMARY_MIN_LENGTH,
    SUMMARY_MAX_LENGTH: ERRORS_CONST.SUMMARY_MAX_LENGTH,
  },
  IS_INCORRECT_LENGTH_TASK_DESCRIPTION: {
    TASK_DESCRIPTION_MAX_LENGTH: ERRORS_CONST.TASK_DESCRIPTION_MAX_LENGTH,
  },

  IS_INCORRECT_LENGTH_KEYWORD: {
    KEYWORD_MIN_LENGTH: ERRORS_CONST.KEYWORD_MIN_LENGTH,
  },
  IS_INCORRECT_LENGTH_COLUMN: {
    COLUMN_MIN_LENGTH: ERRORS_CONST.COLUMN_MIN_LENGTH,
    COLUMN_MAX_LENGTH: ERRORS_CONST.COLUMN_MAX_LENGTH,
  },
  IS_INCORRECT_WORK_LOG_COMMENT: {
    WORK_LOG_COMMENT_MIN_LENGTH: ERRORS_CONST.WORK_LOG_COMMENT_MIN_LENGTH,
    WORK_LOG_COMMENT_MAX_LENGTH: ERRORS_CONST.WORK_LOG_COMMENT_MAX_LENGTH,
  },
};
