export const CREATE_BOARD = "CREATE_BOARD";
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";
export const CREATE_BOARD_ERROR = "CREATE_BOARD_ERROR";

export const GET_BOARD = "GET_BOARD";
export const GET_BOARD_ERROR = "GET_BOARD_ERROR";
export const GET_BOARD_SUCCESS = "GET_BOARD_SUCCESS";
export const GET_BOARD_CLEAR = "GET_BOARD_CLEAR";
