export const CREATE_BOARD = "CREATE_BOARD";
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";
export const CREATE_BOARD_ERROR = "CREATE_BOARD_ERROR";

export const GET_BOARD = "GET_BOARD";
export const GET_BOARD_ERROR = "GET_BOARD_ERROR";
export const GET_BOARD_SUCCESS = "GET_BOARD_SUCCESS";
export const GET_BOARD_CLEAR = "GET_BOARD_CLEAR";

export const GET_BOARDS = "GET_BOARDS";
export const GET_BOARDS_SUCCESS = "GET_BOARDS_SUCCESS";
export const GET_BOARDS_ERROR = "GET_BOARDS_ERROR";
export const GET_BOARDS_CLEAR = "GET_BOARDS_CLEAR";

export const EDIT_BOARD = "EDIT_BOARD";
export const EDIT_BOARD_SUCCESS = "EDIT_BOARD_SUCCESS";
export const EDIT_BOARD_ERROR = "EDIT_BOARD_ERROR";

export const SAVE_MEMBERS = "SAVE_MEMBERS";
export const SAVE_MEMBERS_SUCCESS = "SAVE_MEMBERS_SUCCESS";
export const CLEAR_MEMBERS_SAVED_MEMBERS = "CLEAR_MEMBERS_SAVED_MEMBERS";
