export const CREATE_BOARD = "CREATE_BOARD";
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";
export const CREATE_BOARD_ERROR = "CREATE_BOARD_ERROR";

export const GET_BOARD = "GET_BOARD";
export const GET_BOARD_ERROR = "GET_BOARD_ERROR";
export const GET_BOARD_SUCCESS = "GET_BOARD_SUCCESS";
export const GET_BOARD_CLEAR = "GET_BOARD_CLEAR";

export const GET_BOARDS = "GET_BOARDS";
export const GET_BOARDS_SUCCESS = "GET_BOARDS_SUCCESS";
export const GET_BOARDS_ERROR = "GET_BOARDS_ERROR";
export const GET_BOARDS_CLEAR = "GET_BOARDS_CLEAR";

export const EDIT_BOARD = "EDIT_BOARD";
export const EDIT_BOARD_SUCCESS = "EDIT_BOARD_SUCCESS";
export const EDIT_BOARD_ERROR = "EDIT_BOARD_ERROR";

export const SAVE_MEMBERS = "SAVE_MEMBERS";
export const CLEAR_MEMBERS_SAVED_MEMBERS = "CLEAR_MEMBERS_SAVED_MEMBERS";

export const LEAVE_BOARD = "LEAVE_BOARD";
export const LEAVE_BOARD_SUCCESS = "LEAVE_BOARD_SUCCESS";
export const LEAVE_BOARD_ERROR = "LEAVE_BOARD_ERROR";

export const CHANGE_STATUSES = "CHANGE_STATUSES";
export const CHANGE_STATUSES_SUCCESS = "CHANGE_STATUSES_SUCCESS";
export const CHANGE_STATUSES_ERROR = "CHANGE_STATUSES_ERROR";

export const DELETE_STATUSES = "DELETE_STATUSES";
export const DELETE_STATUSES_SUCCESS = "DELETE_STATUSES_SUCCESS";
export const DELETE_STATUSES_ERROR = "DELETE_STATUSES_ERROR";
