export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENTS_SUCCESS = "ADD_COMMENTS_SUCCESS";
export const ADD_COMMENTS_ERROR = "ADD_COMMENTS_ERROR";

export const GET_TASK_COMMENTS = "GET_TASK_COMMENTS";
export const GET_TASK_COMMENTS_SUCCESS = "GET_TASK_COMMENTS_SUCCESS";
export const GET_TASK_COMMENTS_ERROR = "GET_TASK_COMMENTS_ERROR";
export const GET_TASK_COMMENTS_CLEAR = "GET_TASK_COMMENTS_CLEAR";
