export const ADD_WORK_LOG = "ADD_WORK_LOG";
export const ADD_WORK_LOG_SUCCESS = "ADD_WORK_LOG_SUCCESS";
export const ADD_WORK_LOG_ERROR = "ADD_WORK_LOG_ERROR";

export const GET_LOG_WORK_DATA = "GET_LOG_WORK_DATA";
export const GET_LOG_WORK_DATA_SUCCESS = "GET_LOG_WORK_DATA_SUCCESS";
export const GET_LOG_WORK_DATA_ERROR = "GET_LOG_WORK_DATA_ERROR";
export const GET_LOG_WORK_DATA_CLEAR = "GET_LOG_WORK_DATA_CLEAR";
