export const LOGIN_USER_FB = "LOGIN_USER_FB";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const COMPLETE_PROFILE_FORM = "COMPLETE_PROFILE_FORM";
export const COMPLETE_PROFILE_FORM_SUCCESS = "COMPLETE_PROFILE_FORM_SUCCESS";
export const COMPLETE_PROFILE_FORM_ERROR = "COMPLETE_PROFILE_FORM_ERROR";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";